# Generated by Django 5.1.1 on 2024-09-28 22:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_marcador_texto_marcador_jugador1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marcador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marcador',
            name='jugador1',
            field=models.CharField(default='Jugador 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='marcador',
            name='jugador2',
            field=models.CharField(default='Jugador 2', max_length=200),
        ),
    ]
