# Generated by Django 5.1.1 on 2024-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marcador_created_at_alter_marcador_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcador',
            name='campeonato',
            field=models.CharField(default='World PingPong Tour', max_length=200),
        ),
    ]
