# Generated by Django 5.1.1 on 2024-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marcador_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='campeonato',
            field=models.CharField(max_length=200),
        ),
    ]
