# Generated by Django 5.1.1 on 2024-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_marcador_campeonato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
