# Generated by Django 5.1.1 on 2024-10-26 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_marcador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
