# Generated by Django 5.1.1 on 2024-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_marcador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
